### ISSUE TITLE
Proguard warnings about android.util.FloatMath methods

### ISSUE THREAD

**Issue by calvarez-ov** [frakbot/GlowPadBackport#16]
When setting compileSdkVersion to 23 in my project, proguard shows these warnings:
```
Warning: net.frakbot.glowpadbackport.PointCloud: can't find referenced method 'float cos(float)' in library class android.util.FloatMath
Warning: net.frakbot.glowpadbackport.PointCloud: can't find referenced method 'float sin(float)' in library class android.util.FloatMath
Warning: net.frakbot.glowpadbackport.PointCloud: can't find referenced method 'float sqrt(float)' in library class android.util.FloatMath
```

**Comment by calvarez-ov** [comment]
A PR has already been opened for this: https://github.com/frakbot/GlowPadBackport/pull/15

**Comment by rock3r** [comment]
See the PR for details on why this is not a real issue. If you want to suppress the warnings, add  `-dontwarn net.frakbot.glowpadbackport.**` to your Proguard rules.

**Comment by calvarez-ov** [comment]
For info, a more specific rule seems to suffice to ignore the warning:
```
-dontwarn net.frakbot.glowpadbackport.PointCloud
```

**Comment by rock3r** [comment]
:+1:
