### ISSUE TITLE
set ringing?

### ISSUE THREAD

**Issue by MohsenShafiee** [frakbot/GlowPadBackport#17]
hi
how to set ringing the glowpad?

thanks in advance...

**Comment by rock3r** [comment]
Hello @TheLoyalCruel I am not sure what you mean/what you're asking for, would you care to elaborate please?

**Comment by MohsenShafiee** [comment]
thanks for the quick answer...
I wanted to simulate ringing motions... and a method which calls `glowpad.ping` for example every second!
but I handled it this way:

``` java
CountDownTimer cTimer = new CountDownTimer(15000, 500) {
    public void onTick(long millisUntilFinished) {
        glowPad.ping();
    }

    public void onFinish() {
        finish();
    }
};
cTimer.start();
```

**Comment by rock3r** [comment]
Cool, seems like you sorted yourself out then :) Closing this.
