### ISSUE TITLE
Double unlock required

### ISSUE THREAD

**Issue by lpellegr** [frakbot/GlowPadBackport#9]
I have integrated your great glowpadview backport into one of my app on a lock screen activity. On the `onTrigger` event, a call to `finish` is performed. I have tested it on some devices and it works good. However I have a user who has reported an issue with his phone (Coolpad 8297 - Android 4.2.2):

"When I get an incoming text and I try to unlock the custom lockscreen it suddenly gives me the inner slider lock again but now with a circle around it like it does when sliding to the right. Now I have to slide the slider to the right again, so twice in total to unlock. Unlike once when no incoming texts.

Steps to reproduce are: I get incoming text, I press power button on phone, I wait for custom lock screen to load, I try to unlock, then I have to unlock it again since its somehow stuck when I get a text."

Below is an image sent by the user:
http://imgur.com/3F5VNmA

Unfortunately, I haven't succeeded to reproduce the issue. I post the issue here because it is perhaps related to your backport implementation. In that case you will maybe have an idea about where the issue may come from?

**Comment by rock3r** [comment]
Sorry for taking this long -- hope you fixed this issue in your code. This library is not a lockscreen implementation and as such I can't support that kind of issue as it's not dependent on this view.
